import { escapeAttribute as ea, escapeHtml as e, page } from '../html.js';

type User = { id: string; email: string; name: string | null; role: string };
const nav = (user: User) => `<aside class="admin-nav"><a class="brand" href="/admin">Satu Admin</a><nav><a href="/admin">Обзор</a><a href="/admin/projects">Проекты</a><a href="/admin/leads">Заявки</a>${user.role === 'admin' ? '<a href="/admin/settings">Настройки</a><a href="/admin/users">Пользователи</a>' : ''}<a href="/" target="_blank">Открыть сайт ↗</a></nav><form method="post" action="/admin/logout"><button>Выйти</button></form></aside>`;
const shell = (user: User, title: string, content: string) => page({ title: `${title} — Satu Admin`, bodyClass: 'admin-body', body: `${nav(user)}<main class="admin-main">${content}</main>` });
const status = (value: string) => ({ new: 'Новая', in_progress: 'В работе', done: 'Обработана', rejected: 'Отклонена' }[value] || value);

export function loginPage(error = '', callback = '/admin'): string { return page({ title: 'Вход — Satu Admin', bodyClass: 'login-body', body: `<main class="login-card"><p class="eyebrow">Satu Ordasy</p><h1>Вход в админ-панель</h1>${error ? `<div class="notice notice--error">${e(error)}</div>` : ''}<form method="post" action="/admin/login" class="stack"><input type="hidden" name="callback" value="${ea(callback)}"><label>Email<input name="email" type="email" required autofocus autocomplete="email"></label><label>Пароль<input name="password" type="password" required autocomplete="current-password"></label><button class="button">Войти</button></form></main>` }); }

export function dashboard(user: User, stats: { projects: number; published: number; leads: number; fresh: number }, leads: any[]): string {
  return shell(user, 'Обзор', `<header><p class="eyebrow">Дашборд</p><h1>Здравствуйте, ${e(user.name || user.email)}!</h1></header><div class="stats"><article><strong>${stats.projects}</strong><span>Всего проектов</span></article><article><strong>${stats.published}</strong><span>Опубликовано</span></article><article><strong>${stats.fresh}</strong><span>Новые заявки</span></article><article><strong>${stats.leads}</strong><span>Всего заявок</span></article></div><h2>Последние заявки</h2>${leadTable(leads, false)}`);
}

export function projectsPage(user: User, projects: any[]): string {
  const rows = projects.map(p => `<tr id="project-${ea(p.id)}"><td><strong>${e(p.title)}</strong><small>/zhk/${e(p.slug)}</small></td><td><span class="badge">${p.status === 'published' ? 'Опубликован' : 'Черновик'}</span></td><td>${p._count.leads}</td><td class="actions"><button hx-post="/admin/projects/${ea(p.id)}/toggle" hx-target="#project-${ea(p.id)}" hx-swap="outerHTML">${p.status === 'published' ? 'Снять' : 'Опубликовать'}</button><button class="danger" hx-delete="/admin/projects/${ea(p.id)}" hx-target="#project-${ea(p.id)}" hx-swap="outerHTML" hx-confirm="Удалить проект и связанные данные?">Удалить</button></td></tr>`).join('');
  return shell(user, 'Проекты', `<header><p class="eyebrow">Управление</p><h1>ЖК-проекты</h1></header><div class="table-wrap"><table><thead><tr><th>Проект</th><th>Статус</th><th>Заявки</th><th></th></tr></thead><tbody>${rows}</tbody></table></div>`);
}

function leadTable(leads: any[], editable: boolean): string {
  const rows = leads.map(x => `<tr id="lead-${ea(x.id)}"><td><strong>${e(x.name)}</strong><small>${e(x.phone)}</small></td><td>${e(x.project.title)}</td><td>${new Date(x.createdAt).toLocaleDateString('ru-RU')}</td><td>${editable ? `<select name="status" hx-patch="/admin/leads/${ea(x.id)}" hx-target="#lead-${ea(x.id)}" hx-swap="outerHTML">${['new','in_progress','done','rejected'].map(v => `<option value="${v}" ${v === x.status ? 'selected' : ''}>${status(v)}</option>`).join('')}</select>` : `<span class="badge">${status(x.status)}</span>`}</td>${editable ? `<td><button class="danger" hx-delete="/admin/leads/${ea(x.id)}" hx-target="#lead-${ea(x.id)}" hx-swap="outerHTML" hx-confirm="Удалить заявку?">Удалить</button></td>` : ''}</tr>`).join('');
  return `<div class="table-wrap"><table><thead><tr><th>Клиент</th><th>Проект</th><th>Дата</th><th>Статус</th>${editable ? '<th></th>' : ''}</tr></thead><tbody>${rows}</tbody></table></div>`;
}
export function leadsPage(user: User, leads: any[]): string { return shell(user, 'Заявки', `<header><p class="eyebrow">CRM</p><h1>Заявки с сайтов</h1></header>${leadTable(leads, true)}`); }

export function usersPage(user: User, users: any[]): string {
  const rows = users.map(x => `<tr id="user-${ea(x.id)}"><td><strong>${e(x.name || 'Без имени')}</strong><small>${e(x.email)}</small></td><td>${e(x.role)}</td><td>${x.id === user.id ? 'Текущий пользователь' : `<button class="danger" hx-delete="/admin/users/${ea(x.id)}" hx-target="#user-${ea(x.id)}" hx-swap="outerHTML" hx-confirm="Удалить пользователя?">Удалить</button>`}</td></tr>`).join('');
  return shell(user, 'Пользователи', `<header><p class="eyebrow">Доступ</p><h1>Пользователи</h1></header><form class="inline-form" hx-post="/admin/users" hx-target="#user-result"><input name="name" placeholder="Имя"><input name="email" type="email" placeholder="Email" required><input name="password" type="password" minlength="8" placeholder="Пароль" required><select name="role"><option value="manager">Менеджер</option><option value="admin">Администратор</option></select><button class="button">Добавить</button><div id="user-result"></div></form><div class="table-wrap"><table><tbody>${rows}</tbody></table></div>`);
}

export function projectRow(p: any): string { return `<tr id="project-${ea(p.id)}"><td><strong>${e(p.title)}</strong><small>/zhk/${e(p.slug)}</small></td><td><span class="badge">${p.status === 'published' ? 'Опубликован' : 'Черновик'}</span></td><td>${p._count.leads}</td><td class="actions"><button hx-post="/admin/projects/${ea(p.id)}/toggle" hx-target="#project-${ea(p.id)}" hx-swap="outerHTML">${p.status === 'published' ? 'Снять' : 'Опубликовать'}</button><button class="danger" hx-delete="/admin/projects/${ea(p.id)}" hx-target="#project-${ea(p.id)}" hx-swap="outerHTML" hx-confirm="Удалить проект?">Удалить</button></td></tr>`; }
export function leadRow(x: any): string { return `<tr id="lead-${ea(x.id)}"><td><strong>${e(x.name)}</strong><small>${e(x.phone)}</small></td><td>${e(x.project.title)}</td><td>${new Date(x.createdAt).toLocaleDateString('ru-RU')}</td><td><select name="status" hx-patch="/admin/leads/${ea(x.id)}" hx-target="#lead-${ea(x.id)}" hx-swap="outerHTML">${['new','in_progress','done','rejected'].map(v => `<option value="${v}" ${v === x.status ? 'selected' : ''}>${status(v)}</option>`).join('')}</select></td><td><button class="danger" hx-delete="/admin/leads/${ea(x.id)}" hx-target="#lead-${ea(x.id)}" hx-swap="outerHTML">Удалить</button></td></tr>`; }

const field = (label: string, name: string, value: unknown = '', type = 'text') => `<label>${e(label)}<input name="${ea(name)}" type="${ea(type)}" value="${ea(value)}"></label>`;
const area = (label: string, name: string, value: unknown = '') => `<label class="wide">${e(label)}<textarea name="${ea(name)}" rows="4">${e(value)}</textarea></label>`;
const editor = (title: string, action: string, fields: string) => `<section class="editor-card"><h2>${e(title)}</h2><form class="editor-grid" hx-post="${ea(action)}" hx-target="find .form-result" hx-swap="innerHTML">${fields}<button class="button wide">Сохранить</button><div class="form-result wide"></div></form></section>`;
const collection = (title: string, action: string, items: any[], fields: string, render: (x: any) => string) => `<section class="editor-card"><h2>${e(title)}</h2><div class="collection">${items.map(render).join('') || '<p>Пока пусто.</p>'}</div><form class="editor-grid" hx-post="${ea(action)}" hx-target="find .form-result" hx-swap="innerHTML">${fields}<button class="button wide">Добавить</button><div class="form-result wide"></div></form></section>`;

export function newProjectPage(user: User): string {
  return shell(user, 'Новый проект', `<header><a href="/admin/projects">← Все проекты</a><h1>Новый проект ЖК</h1></header><section class="editor-card"><form class="editor-grid" method="post" action="/admin/projects">${field('Название','title')}${field('Slug','slug')}<label>Статус<select name="status"><option value="draft">Черновик</option><option value="published">Опубликован</option></select></label>${field('SEO Title','seoTitle')}${area('SEO Description','seoDescription')}<button class="button wide">Создать проект</button></form></section>`);
}

export function projectEditorPage(user: User, p: any): string {
  const remove = (kind: string, x: any, label: string) => `<div id="${kind}-${ea(x.id)}" class="collection-item"><span>${e(label)}</span><button class="danger" hx-delete="/admin/content/${kind}/${ea(x.id)}" hx-target="#${kind}-${ea(x.id)}" hx-swap="outerHTML" hx-confirm="Удалить?">Удалить</button></div>`;
  const upload = `<label class="wide">Загрузить файл<input type="file" name="file" hx-post="/admin/upload" hx-encoding="multipart/form-data" hx-target="next .upload-result"></label><div class="upload-result wide"></div>`;
  const base = editor('Основные настройки', `/admin/projects/${p.id}/base`, `${field('Название','title',p.title)}${field('Slug','slug',p.slug)}<label>Статус<select name="status"><option value="draft" ${p.status === 'draft' ? 'selected' : ''}>Черновик</option><option value="published" ${p.status === 'published' ? 'selected' : ''}>Опубликован</option></select></label>${field('Тема','themePreset',p.themePreset)}${field('Шрифт','fontPreset',p.fontPreset)}${field('SEO Title','seoTitle',p.seoTitle)}${area('SEO Description','seoDescription',p.seoDescription)}${field('Ключевые слова','seoKeywords',p.seoKeywords)}${field('OG Image URL','ogImageUrl',p.ogImageUrl)}${field('Город','geoCity',p.geoCity)}${field('Регион','geoRegion',p.geoRegion)}`);
  const hero = editor('Главный экран', `/admin/projects/${p.id}/hero`, `${field('Заголовок','title',p.hero?.title)}${area('Подзаголовок','subtitle',p.hero?.subtitle)}${field('Текст кнопки','ctaText',p.hero?.ctaText || 'Оставить заявку')}${field('Десктоп-изображение','desktopImage',p.hero?.desktopImage)}${field('Мобильное изображение','mobileImage',p.hero?.mobileImage)}${upload}`);
  const about = editor('О проекте', `/admin/projects/${p.id}/about`, `${area('Описание','description',p.about?.description)}${field('URL карты','mapEmbedUrl',p.about?.mapEmbedUrl)}${field('Широта','mapLat',p.about?.mapLat,'number')}${field('Долгота','mapLng',p.about?.mapLng,'number')}`);
  const nearby = p.about ? collection('Инфраструктура рядом', `/admin/projects/${p.id}/nearby`, p.about.nearby, `${field('Название','name')}${field('Расстояние','distance')}`, x => remove('nearby',x,`${x.name} — ${x.distance}`)) : '<section class="editor-card"><p>Сначала сохраните раздел «О проекте».</p></section>';
  const advantages = collection('Преимущества', `/admin/projects/${p.id}/advantages`, p.advantages, `${field('Заголовок','title')}${area('Описание','description')}${field('Иконка','icon')}`, x => remove('advantage',x,x.title));
  const gallery = collection('Галерея', `/admin/projects/${p.id}/gallery`, p.gallery, `${field('URL изображения','url')}${field('Подпись','caption')}${upload}`, x => remove('gallery',x,x.caption || x.url));
  const interiors = collection('Интерьеры', `/admin/projects/${p.id}/interiors`, p.interiors, `${field('URL изображения','imageUrl')}${field('Подпись','caption')}${area('Описание','description')}${upload}`, x => remove('interior',x,x.caption || x.imageUrl));
  const floors = `<section class="editor-card"><h2>Планировки</h2><div class="collection">${p.floorCategories.map((c:any)=>`<div class="floor-category"><div class="collection-item"><strong>${e(c.name)}</strong><button class="danger" hx-delete="/admin/content/floor-category/${ea(c.id)}" hx-target="closest .floor-category" hx-swap="outerHTML" hx-confirm="Удалить категорию и планировки?">Удалить</button></div>${c.units.map((x:any)=>remove('floor-unit',x,`${x.name||c.name} — ${x.area} м²`)).join('')}<form class="editor-grid compact" hx-post="/admin/floor-categories/${ea(c.id)}/units" hx-target="find .form-result">${field('Название','name')}${field('Площадь, м²','area','','number')}${field('URL изображения','imageUrl')}<button class="button">Добавить планировку</button><div class="form-result wide"></div></form></div>`).join('')}</div><form class="editor-grid" hx-post="/admin/projects/${ea(p.id)}/floor-categories" hx-target="find .form-result">${field('Название категории','name')}<button class="button">Добавить категорию</button><div class="form-result wide"></div></form></section>`;
  const socials = collection('Социальные сети', `/admin/projects/${p.id}/socials`, p.socials, `${field('Платформа','platform')}${field('URL','url')}`, x => remove('social',x,x.platform));
  const catalog = editor('Каталог', `/admin/projects/${p.id}/catalog`, `${field('URL файла','fileUrl',p.catalog?.fileUrl)}${field('Имя файла','fileName',p.catalog?.fileName)}${upload}`);
  const lead = editor('Форма заявки', `/admin/projects/${p.id}/lead-form`, `<label>Тип<select name="formType"><option value="native" ${p.leadForm?.formType !== 'bitrix24' ? 'selected' : ''}>Встроенная</option><option value="bitrix24" ${p.leadForm?.formType === 'bitrix24' ? 'selected' : ''}>Bitrix24</option></select></label>${field('Заголовок','sectionTitle',p.leadForm?.sectionTitle)}${area('Подзаголовок','sectionSubtitle',p.leadForm?.sectionSubtitle)}${field('Bitrix portal ID','bitrixPortalId',p.leadForm?.bitrixPortalId)}${field('Bitrix form ID','bitrixFormId',p.leadForm?.bitrixFormId)}${area('Bitrix embed code','bitrixEmbedCode',p.leadForm?.bitrixEmbedCode)}`);
  return shell(user, p.title, `<header><a href="/admin/projects">← Все проекты</a><h1>${e(p.title)}</h1><a href="/zhk/${ea(p.slug)}" target="_blank">Открыть страницу ↗</a></header><div class="editors">${base}${hero}${about}${nearby}${advantages}${gallery}${floors}${interiors}${catalog}${lead}${socials}</div>`);
}

export function settingsPage(user: User, values: Record<string,string>, home: any, privacy: string): string {
  return shell(user, 'Настройки', `<header><p class="eyebrow">Платформа</p><h1>Настройки сайта</h1></header>${editor('Бренд и SEO','/admin/settings',`${field('Название бренда','brandName',values.brandName)}${field('Favicon URL','faviconUrl',values.faviconUrl)}${field('GTM Container ID','gtmContainerId',values.gtmContainerId)}${field('Город по умолчанию','geoDefaultCity',values.geoDefaultCity)}${area('Дополнительные robots.txt','robotsCustomRules',values.robotsCustomRules)}`)}${editor('Главная страница','/admin/settings/home',`${field('Заголовок','title',home?.title)}${area('Подзаголовок','subtitle',home?.subtitle)}${field('Hero image','heroImage',home?.heroImage)}${field('Логотип','logoUrl',home?.logoUrl)}`)}${editor('Политика конфиденциальности','/admin/settings/privacy',area('Текст','content',privacy))}`);
}
