import type { Prisma } from '@prisma/client';
import type { projectInclude } from '../db.js';
import { escapeAttribute as ea, escapeHtml as e, page, safeUrl as u } from '../html.js';
import { getFontPreset, getThemePreset } from '../../src/lib/theme-presets.js';
import { sanitizeEmbedCode } from '../validation.js';

type Project = Prisma.ProjectGetPayload<{ include: typeof projectInclude }>;
type Social = { id: string; platform: string; url: string };
const img = (url: string | null | undefined, alt: string, cls = '') => u(url) ? `<img src="${u(url)}" alt="${ea(alt)}" class="${cls}" loading="lazy" decoding="async">` : '';
const header = (title: string) => `<header class="site-header"><div class="shell header-row"><a class="brand" href="/">${e(title)}</a><nav aria-label="Основная навигация"><a href="#about">О проекте</a><a href="#gallery">Галерея</a><a href="#plans">Планировки</a><a class="button button--small" href="#lead-form">Оставить заявку</a></nav></div></header>`;
const footer = (brand: string, socials: Social[]) => `<footer class="footer"><div class="shell footer-row"><div><strong>${e(brand)}</strong><p>Выберите свой идеальный дом</p></div><div class="footer-links">${socials.map(s => `<a href="${u(s.url)}" rel="noopener noreferrer" target="_blank">${e(s.platform)}</a>`).join('')}<a href="/privacy">Политика конфиденциальности</a></div></div></footer>`;

export function homePage(input: { projects: Array<{ slug: string; title: string; seoDescription: string | null; hero: { desktopImage: string | null; mobileImage: string | null; subtitle: string | null } | null }>; home: { title: string; subtitle: string | null; heroImage: string | null; logoUrl: string | null }; socials: Social[] }): string {
  const cards = input.projects.map(p => `<article class="project-card"><a href="/zhk/${encodeURIComponent(p.slug)}"><div class="project-card__media">${img(p.hero?.desktopImage || p.hero?.mobileImage, p.title, 'cover')}</div><div class="project-card__body"><p class="eyebrow">Жилой комплекс</p><h3>${e(p.title)}</h3><p>${e(p.hero?.subtitle || p.seoDescription || '')}</p><span class="text-link">Открыть проект →</span></div></a></article>`).join('');
  return page({ title: input.home.title, description: input.home.subtitle || '', body: `${header(input.home.title)}<main><section class="home-hero">${img(input.home.heroImage, input.home.title, 'home-hero__image')}<div class="home-hero__shade"></div><div class="shell home-hero__content"><p class="eyebrow">Выберите свой идеальный дом</p><h1>${e(input.home.title)}</h1>${input.home.subtitle ? `<p>${e(input.home.subtitle)}</p>` : ''}</div></section><section class="section shell"><div class="section-heading"><p class="eyebrow">Недвижимость</p><h2>Наши проекты</h2><p>Каждый проект — отдельная история с собственным оформлением и характером.</p></div><div class="project-grid">${cards || '<p class="empty">Пока нет опубликованных проектов.</p>'}</div></section></main>${footer(input.home.title, input.socials)}` });
}

export function projectPage(p: Project, brand: string, globalSocials: Social[]): string {
  const theme = getThemePreset(p.themePreset), font = getFontPreset(p.fontPreset);
  const style = `${Object.entries(theme.cssVars).map(([k, v]) => `${k}:${v}`).join(';')};--font-sans:${font.stack}`;
  const advantages = p.advantages.map((x, i) => `<article class="feature"><span class="feature__number">${String(i + 1).padStart(2, '0')}</span><h3>${e(x.title)}</h3><p>${e(x.description)}</p></article>`).join('');
  const nearby = p.about?.nearby.map(x => `<li><span>${e(x.name)}</span><strong>${e(x.distance)}</strong></li>`).join('') || '';
  const gallery = p.gallery.map(x => `<figure class="gallery__item">${img(x.url, x.caption || p.title, 'cover')}${x.caption ? `<figcaption>${e(x.caption)}</figcaption>` : ''}</figure>`).join('');
  const plans = p.floorCategories.map(c => `<section class="plan-group"><h3>${e(c.name)}</h3><div class="plan-grid">${c.units.map(x => `<article class="plan-card">${img(x.imageUrl, x.name || c.name)}<div><strong>${e(x.name || c.name)}</strong><span>${e(x.area)} м²</span></div></article>`).join('')}</div></section>`).join('');
  const interiors = p.interiors.map(x => `<figure>${img(x.imageUrl, x.caption || 'Интерьер', 'cover')}${x.caption ? `<figcaption>${e(x.caption)}</figcaption>` : ''}</figure>`).join('');
  const lead = p.leadForm?.formType === 'bitrix24' ? sanitizeEmbedCode(p.leadForm.bitrixEmbedCode || '') : `<form class="lead-form" hx-post="/api/leads" hx-target="#lead-result" hx-swap="innerHTML" hx-disabled-elt="button"><input type="hidden" name="projectId" value="${ea(p.id)}"><label>Имя<input name="name" autocomplete="name" minlength="2" required></label><label>Телефон<input name="phone" type="tel" autocomplete="tel" minlength="7" required></label><label class="wide">Комментарий<textarea name="comment" rows="4"></textarea></label><label class="wide consent"><input type="checkbox" name="consent" value="yes" required> Я принимаю <a href="/privacy" target="_blank">политику конфиденциальности</a></label><button class="button wide" type="submit">Отправить заявку</button><div id="lead-result" class="wide"></div></form>`;
  return page({ title: p.seoTitle || p.title, description: p.seoDescription || '', bodyClass: theme.isDark ? 'dark' : '', style, body: `${header(p.title)}<main>
  ${p.hero ? `<section class="project-hero">${img(p.hero.desktopImage || p.hero.mobileImage, p.hero.title, 'project-hero__image')}<div class="project-hero__shade"></div><div class="shell project-hero__content"><p class="eyebrow">Жилой комплекс</p><h1>${e(p.hero.title)}</h1>${p.hero.subtitle ? `<p>${e(p.hero.subtitle)}</p>` : ''}<a class="button" href="#lead-form">${e(p.hero.ctaText)}</a></div></section>` : ''}
  ${advantages ? `<section class="section shell"><div class="section-heading"><p class="eyebrow">Преимущества</p><h2>Всё важное рядом</h2></div><div class="feature-grid">${advantages}</div></section>` : ''}
  ${p.about ? `<section id="about" class="section section--muted"><div class="shell about-grid"><div><p class="eyebrow">О проекте</p><h2>${e(p.title)}</h2><div class="prose">${e(p.about.description).replaceAll('\n', '<br>')}</div></div>${nearby ? `<ul class="nearby">${nearby}</ul>` : ''}</div></section>` : ''}
  ${gallery ? `<section id="gallery" class="section shell"><div class="section-heading"><p class="eyebrow">Архитектура</p><h2>Галерея</h2></div><div class="gallery">${gallery}</div></section>` : ''}
  ${plans ? `<section id="plans" class="section section--muted"><div class="shell"><div class="section-heading"><p class="eyebrow">Ваш новый дом</p><h2>Планировки</h2></div>${plans}${p.catalog ? `<a class="button button--outline" href="${u(p.catalog.fileUrl)}" download>Скачать каталог</a>` : ''}</div></section>` : ''}
  ${interiors ? `<section class="section shell"><div class="section-heading"><p class="eyebrow">Детали</p><h2>Интерьеры</h2></div><div class="interior-grid">${interiors}</div></section>` : ''}
  <section id="lead-form" class="section lead-section"><div class="shell lead-grid"><div><p class="eyebrow">Связаться с нами</p><h2>${e(p.leadForm?.sectionTitle || 'Оставьте заявку на просмотр')}</h2><p>${e(p.leadForm?.sectionSubtitle || 'Менеджер свяжется с вами и ответит на вопросы.')}</p></div>${lead}</div></section></main>${footer(brand, p.socials.length ? p.socials : globalSocials)}` });
}

export function privacyPage(title: string, content: string): string { return page({ title: `Политика конфиденциальности — ${title}`, body: `${header(title)}<main class="section shell narrow"><p class="eyebrow">Документы</p><h1>Политика конфиденциальности</h1><div class="prose privacy">${e(content).replaceAll('\n', '<br>')}</div></main>${footer(title, [])}` }); }
